package gui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lencii
 */
public class ContactsManager extends javax.swing.JFrame {

    /**
     * Creates new form ContactsManager
     */
    public ContactsManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogGroup = new javax.swing.JDialog();
        jLabelNewEditGroup = new javax.swing.JLabel();
        jLabelGroupType = new javax.swing.JLabel();
        jComboBoxGroupType = new javax.swing.JComboBox();
        jLabelGroupNote = new javax.swing.JLabel();
        jTextFieldGroupNote = new javax.swing.JTextField();
        jButtonGroupCancel = new javax.swing.JButton();
        jButtonGroupOK = new javax.swing.JButton();
        jDialogDeleteGroup = new javax.swing.JDialog();
        jLabelDeleteGroup = new javax.swing.JLabel();
        jLabelDeleteGroupType = new javax.swing.JLabel();
        jComboBoxDeleteGroup = new javax.swing.JComboBox();
        jButtonDeleteGroupOK = new javax.swing.JButton();
        jButtonDeleteGroupCancel = new javax.swing.JButton();
        jDialogContact = new javax.swing.JDialog();
        jLabelEditContact = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelSurname = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldSurname = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jPanelAddToGroup = new javax.swing.JPanel();
        jLabelAddToGroup = new javax.swing.JLabel();
        jCheckBoxFamily = new javax.swing.JCheckBox();
        jCheckBoxFriends = new javax.swing.JCheckBox();
        jCheckBoxWork = new javax.swing.JCheckBox();
        jCheckBoxOther = new javax.swing.JCheckBox();
        jLabelNumbers = new javax.swing.JLabel();
        jPanelNumbers = new javax.swing.JPanel();
        jComboBoxNumbers1 = new javax.swing.JComboBox();
        jComboBoxNumbers2 = new javax.swing.JComboBox();
        jComboBoxNumbers3 = new javax.swing.JComboBox();
        jComboBoxNumbers4 = new javax.swing.JComboBox();
        jComboBoxNumbers5 = new javax.swing.JComboBox();
        jTextFieldNumbers1 = new javax.swing.JTextField();
        jTextFieldNumbers2 = new javax.swing.JTextField();
        jTextFieldNumbers3 = new javax.swing.JTextField();
        jTextFieldNumbers4 = new javax.swing.JTextField();
        jTextFieldNumbers5 = new javax.swing.JTextField();
        jButtonContactOK = new javax.swing.JButton();
        jButtonContactCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jShowGroup = new javax.swing.JComboBox();
        jNote = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContact = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNumber = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelContact = new javax.swing.JLabel();
        jButtonNewContact = new javax.swing.JButton();
        jButtonEditContact = new javax.swing.JButton();
        jButtonDeleteContact = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelGroup = new javax.swing.JLabel();
        jButtonNewGroup = new javax.swing.JButton();
        jButtonEditGroup = new javax.swing.JButton();
        jButtonDeleteGroup = new javax.swing.JButton();
        jSearchField = new javax.swing.JTextField();
        jSearchButton = new javax.swing.JButton();

        jLabelNewEditGroup.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelNewEditGroup.setText("GROUP");

        jLabelGroupType.setText("Type:");

        jComboBoxGroupType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelGroupNote.setText("Note:");

        jTextFieldGroupNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGroupNoteActionPerformed(evt);
            }
        });

        jButtonGroupCancel.setText("Cancel");

        jButtonGroupOK.setText("OK");
        jButtonGroupOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGroupOKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialogGroupLayout = new javax.swing.GroupLayout(jDialogGroup.getContentPane());
        jDialogGroup.getContentPane().setLayout(jDialogGroupLayout);
        jDialogGroupLayout.setHorizontalGroup(
            jDialogGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogGroupLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabelNewEditGroup)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogGroupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGroupCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGroupOK)
                .addGap(22, 22, 22))
            .addGroup(jDialogGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogGroupLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(jDialogGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelGroupType)
                        .addComponent(jLabelGroupNote))
                    .addGap(38, 38, 38)
                    .addGroup(jDialogGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxGroupType, 0, 194, Short.MAX_VALUE)
                        .addComponent(jTextFieldGroupNote))
                    .addContainerGap(99, Short.MAX_VALUE)))
        );
        jDialogGroupLayout.setVerticalGroup(
            jDialogGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogGroupLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelNewEditGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addGroup(jDialogGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGroupCancel)
                    .addComponent(jButtonGroupOK))
                .addContainerGap())
            .addGroup(jDialogGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogGroupLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addGroup(jDialogGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelGroupType)
                        .addComponent(jComboBoxGroupType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(jDialogGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelGroupNote)
                        .addComponent(jTextFieldGroupNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(109, Short.MAX_VALUE)))
        );

        jLabelDeleteGroup.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelDeleteGroup.setText("DELETE GROUP");

        jLabelDeleteGroupType.setText("Type:");

        jComboBoxDeleteGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonDeleteGroupOK.setText("OK");
        jButtonDeleteGroupOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteGroupOKMouseClicked(evt);
            }
        });

        jButtonDeleteGroupCancel.setText("Cancel");
        jButtonDeleteGroupCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteGroupCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialogDeleteGroupLayout = new javax.swing.GroupLayout(jDialogDeleteGroup.getContentPane());
        jDialogDeleteGroup.getContentPane().setLayout(jDialogDeleteGroupLayout);
        jDialogDeleteGroupLayout.setHorizontalGroup(
            jDialogDeleteGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDeleteGroupLayout.createSequentialGroup()
                .addGroup(jDialogDeleteGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogDeleteGroupLayout.createSequentialGroup()
                        .addGroup(jDialogDeleteGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDialogDeleteGroupLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabelDeleteGroup))
                            .addGroup(jDialogDeleteGroupLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabelDeleteGroupType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxDeleteGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogDeleteGroupLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonDeleteGroupCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteGroupOK)))
                .addContainerGap())
        );
        jDialogDeleteGroupLayout.setVerticalGroup(
            jDialogDeleteGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDeleteGroupLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelDeleteGroup)
                .addGap(32, 32, 32)
                .addGroup(jDialogDeleteGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDeleteGroupType)
                    .addComponent(jComboBoxDeleteGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jDialogDeleteGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeleteGroupOK)
                    .addComponent(jButtonDeleteGroupCancel))
                .addContainerGap())
        );

        jLabelEditContact.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelEditContact.setText("CONTACT");

        jLabelName.setText("Name:");

        jLabelSurname.setText("Surname:");

        jLabelAddress.setText("Address:");

        jPanelAddToGroup.setBackground(new java.awt.Color(254, 254, 254));
        jPanelAddToGroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelAddToGroup.setText("Add to group");

        jCheckBoxFamily.setText("Family");

        jCheckBoxFriends.setText("Friends");

        jCheckBoxWork.setText("Work");

        jCheckBoxOther.setText("Other");

        javax.swing.GroupLayout jPanelAddToGroupLayout = new javax.swing.GroupLayout(jPanelAddToGroup);
        jPanelAddToGroup.setLayout(jPanelAddToGroupLayout);
        jPanelAddToGroupLayout.setHorizontalGroup(
            jPanelAddToGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddToGroupLayout.createSequentialGroup()
                .addGroup(jPanelAddToGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddToGroupLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelAddToGroup))
                    .addGroup(jPanelAddToGroupLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBoxFamily))
                    .addGroup(jPanelAddToGroupLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBoxFriends))
                    .addGroup(jPanelAddToGroupLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBoxWork))
                    .addGroup(jPanelAddToGroupLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBoxOther)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanelAddToGroupLayout.setVerticalGroup(
            jPanelAddToGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddToGroupLayout.createSequentialGroup()
                .addComponent(jLabelAddToGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFamily)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFriends)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxWork)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxOther)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelNumbers.setText("Numbers:");

        jPanelNumbers.setBackground(new java.awt.Color(254, 254, 254));
        jPanelNumbers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jComboBoxNumbers1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxNumbers2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxNumbers3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxNumbers4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxNumbers5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelNumbersLayout = new javax.swing.GroupLayout(jPanelNumbers);
        jPanelNumbers.setLayout(jPanelNumbersLayout);
        jPanelNumbersLayout.setHorizontalGroup(
            jPanelNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumbersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxNumbers5, 0, 110, Short.MAX_VALUE)
                    .addComponent(jComboBoxNumbers4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxNumbers3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxNumbers2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxNumbers1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNumbers1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumbers2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumbers3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumbers4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumbers5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelNumbersLayout.setVerticalGroup(
            jPanelNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumbersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNumbers1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumbers1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNumbers2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumbers2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNumbers3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumbers3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNumbers4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumbers4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNumbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNumbers5)
                    .addComponent(jTextFieldNumbers5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonContactOK.setText("OK");
        jButtonContactOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonContactOKMouseClicked(evt);
            }
        });

        jButtonContactCancel.setText("Cancel");
        jButtonContactCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonContactCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialogContactLayout = new javax.swing.GroupLayout(jDialogContact.getContentPane());
        jDialogContact.getContentPane().setLayout(jDialogContactLayout);
        jDialogContactLayout.setHorizontalGroup(
            jDialogContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogContactLayout.createSequentialGroup()
                .addGroup(jDialogContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogContactLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonContactCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonContactOK))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialogContactLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jDialogContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDialogContactLayout.createSequentialGroup()
                                .addGroup(jDialogContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogContactLayout.createSequentialGroup()
                                        .addComponent(jLabelSurname)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogContactLayout.createSequentialGroup()
                                        .addComponent(jLabelName)
                                        .addGap(62, 62, 62)
                                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(59, 59, 59)
                                .addComponent(jPanelAddToGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogContactLayout.createSequentialGroup()
                                .addGroup(jDialogContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAddress)
                                    .addComponent(jLabelNumbers))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jDialogContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jDialogContactLayout.createSequentialGroup()
                                        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(190, 190, 190))
                                    .addComponent(jPanelNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(40, 40, 40))
            .addGroup(jDialogContactLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabelEditContact)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogContactLayout.setVerticalGroup(
            jDialogContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogContactLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelEditContact)
                .addGap(18, 18, 18)
                .addGroup(jDialogContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialogContactLayout.createSequentialGroup()
                        .addGroup(jDialogContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialogContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSurname)
                            .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jDialogContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAddress)
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelAddToGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jDialogContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumbers)
                    .addComponent(jPanelNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jDialogContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonContactOK)
                    .addComponent(jButtonContactCancel))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("CONTACTS MANAGER");

        jShowGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jShowGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jShowGroupMouseClicked(evt);
            }
        });

        jNote.setEditable(false);
        jNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoteActionPerformed(evt);
            }
        });

        jTableContact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "SURNAME", "NAME", "ADDRESS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableContact);
        jTableContact.getColumnModel().getColumn(1).setResizable(false);

        jTableNumber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "TYPE", "NUMBER"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableNumber);

        jPanel1.setBackground(new java.awt.Color(207, 204, 201));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelContact.setText("CONTACT");

        jButtonNewContact.setText("New");
        jButtonNewContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNewContactMouseClicked(evt);
            }
        });

        jButtonEditContact.setText("Edit");
        jButtonEditContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditContactMouseClicked(evt);
            }
        });

        jButtonDeleteContact.setText("Delete");
        jButtonDeleteContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteContactMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonNewContact, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jButtonEditContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelContact, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNewContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(207, 204, 201));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelGroup.setText("   GROUP");

        jButtonNewGroup.setText("New");
        jButtonNewGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNewGroupMouseClicked(evt);
            }
        });

        jButtonEditGroup.setText("Edit");
        jButtonEditGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditGroupMouseClicked(evt);
            }
        });

        jButtonDeleteGroup.setText("Delete");
        jButtonDeleteGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteGroupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonNewGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jButtonEditGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNewGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSearchButton.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSearchButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNote)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jShowGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jShowGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchButton))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNoteActionPerformed

    private void jButtonNewGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNewGroupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewGroupMouseClicked

    private void jButtonEditGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditGroupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditGroupMouseClicked

    private void jButtonDeleteGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteGroupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteGroupMouseClicked

    private void jButtonNewContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNewContactMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewContactMouseClicked

    private void jButtonEditContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditContactMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditContactMouseClicked

    private void jButtonDeleteContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteContactMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteContactMouseClicked

    private void jShowGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowGroupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jShowGroupMouseClicked

    private void jTextFieldGroupNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGroupNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGroupNoteActionPerformed

    private void jButtonGroupOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGroupOKMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGroupOKMouseClicked

    private void jButtonDeleteGroupOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteGroupOKMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteGroupOKMouseClicked

    private void jButtonDeleteGroupCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteGroupCancelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteGroupCancelMouseClicked

    private void jButtonContactOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContactOKMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContactOKMouseClicked

    private void jButtonContactCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContactCancelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContactCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactsManager().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContactCancel;
    private javax.swing.JButton jButtonContactOK;
    private javax.swing.JButton jButtonDeleteContact;
    private javax.swing.JButton jButtonDeleteGroup;
    private javax.swing.JButton jButtonDeleteGroupCancel;
    private javax.swing.JButton jButtonDeleteGroupOK;
    private javax.swing.JButton jButtonEditContact;
    private javax.swing.JButton jButtonEditGroup;
    private javax.swing.JButton jButtonGroupCancel;
    private javax.swing.JButton jButtonGroupOK;
    private javax.swing.JButton jButtonNewContact;
    private javax.swing.JButton jButtonNewGroup;
    private javax.swing.JCheckBox jCheckBoxFamily;
    private javax.swing.JCheckBox jCheckBoxFriends;
    private javax.swing.JCheckBox jCheckBoxOther;
    private javax.swing.JCheckBox jCheckBoxWork;
    private javax.swing.JComboBox jComboBoxDeleteGroup;
    private javax.swing.JComboBox jComboBoxGroupType;
    private javax.swing.JComboBox jComboBoxNumbers1;
    private javax.swing.JComboBox jComboBoxNumbers2;
    private javax.swing.JComboBox jComboBoxNumbers3;
    private javax.swing.JComboBox jComboBoxNumbers4;
    private javax.swing.JComboBox jComboBoxNumbers5;
    private javax.swing.JDialog jDialogContact;
    private javax.swing.JDialog jDialogDeleteGroup;
    private javax.swing.JDialog jDialogGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddToGroup;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelDeleteGroup;
    private javax.swing.JLabel jLabelDeleteGroupType;
    private javax.swing.JLabel jLabelEditContact;
    private javax.swing.JLabel jLabelGroup;
    private javax.swing.JLabel jLabelGroupNote;
    private javax.swing.JLabel jLabelGroupType;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNewEditGroup;
    private javax.swing.JLabel jLabelNumbers;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JTextField jNote;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAddToGroup;
    private javax.swing.JPanel jPanelNumbers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchField;
    private javax.swing.JComboBox jShowGroup;
    private javax.swing.JTable jTableContact;
    private javax.swing.JTable jTableNumber;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldGroupNote;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNumbers1;
    private javax.swing.JTextField jTextFieldNumbers2;
    private javax.swing.JTextField jTextFieldNumbers3;
    private javax.swing.JTextField jTextFieldNumbers4;
    private javax.swing.JTextField jTextFieldNumbers5;
    private javax.swing.JTextField jTextFieldSurname;
    // End of variables declaration//GEN-END:variables
}
